### ISSUE TITLE
Deck veröffentlichen nicht möglich.

### ISSUE THREAD

**Issue by Elgoist** [Scriptkiddi/Ankipubsub-Client#24]
Ich habe versucht ein Deck zu veröffentlichen.
Das Deck hatte Karten und ich habe alle Kominationen aus gesetzten und nicht gesetzten Passwörtern versucht. Der Account stimmt, denn die Meldung das Account/PW falsch ist, kommt nicht.

In einem Add-On trat ein Fehler auf.
Bitte posten Sie ihn im Add-On-Forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\Frieder\Documents\Anki\addons\pubsub\gui.py", line 141, in publishDeckGuiOk
    mw.col.conf.get('pubSubPassword', ""))
  File "C:\Users\Frieder\Documents\Anki\addons\pubsub\database.py", line 116, in upload
    remoteDeck = server.push_deck(localDeckToPush)
  File "C:\Users\Frieder\Documents\Anki\addons\pubsub\connectionhandler.py", line 72, in push_deck
    deck = AnkipubSubDeck.fromJsonObject(deckResponse.json())
  File "C:\Users\Frieder\Documents\Anki\addons\pubsub\requests\models.py", line 767, in json
    return json.loads(self.text, **kwargs)
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/json", line 326, in loads
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/json.decoder", line 366, in decode
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/json.decoder", line 384, in raw_decode
ValueError: No JSON object could be decoded

**Comment by Scriptkiddi** [comment]
war das ganze mit read passwort?

**Comment by Elgoist** [comment]
Ich habe es mit allen Kombinationen versucht.
kein Passwort, beide Passwörter oder eines von beiden.

**Comment by Scriptkiddi** [comment]
ah stimmt ich mach mal den server an

**Comment by Elgoist** [comment]
Ich sag dazu mal nix. Wobei...

Bugreport: Es fehlt eine Anzeige für einen nicht erreichbaren Server :D

**Comment by Scriptkiddi** [comment]
hm ja ich stell das ganze jetzt mal auf n celery task dann läuft es als
service und wenn ich noch sentry dazu schalte bekomm ich die fehler auch mit
